import cv2

cap = cv2.VideoCapture(0)

# 代表的なパラメータ一覧
params = {
    "POS_MSEC": cv2.CAP_PROP_POS_MSEC,
    "POS_FRAMES": cv2.CAP_PROP_POS_FRAMES,
    "POS_AVI_RATIO": cv2.CAP_PROP_POS_AVI_RATIO,
    "FRAME_WIDTH": cv2.CAP_PROP_FRAME_WIDTH,
    "FRAME_HEIGHT": cv2.CAP_PROP_FRAME_HEIGHT,
    "FPS": cv2.CAP_PROP_FPS,
    "FOURCC": cv2.CAP_PROP_FOURCC,
    "FRAME_COUNT": cv2.CAP_PROP_FRAME_COUNT,
    "FORMAT": cv2.CAP_PROP_FORMAT,
    "MODE": cv2.CAP_PROP_MODE,
    "BRIGHTNESS": cv2.CAP_PROP_BRIGHTNESS,
    "CONTRAST": cv2.CAP_PROP_CONTRAST,
    "SATURATION": cv2.CAP_PROP_SATURATION,
    "HUE": cv2.CAP_PROP_HUE,
    "GAIN": cv2.CAP_PROP_GAIN,
    "EXPOSURE": cv2.CAP_PROP_EXPOSURE,
    "AUTO_EXPOSURE": cv2.CAP_PROP_AUTO_EXPOSURE,
    "CONVERT_RGB": cv2.CAP_PROP_CONVERT_RGB,
    "WHITE_BALANCE_BLUE_U": cv2.CAP_PROP_WHITE_BALANCE_BLUE_U,
    "WHITE_BALANCE_RED_V": cv2.CAP_PROP_WHITE_BALANCE_RED_V,
    "RECTIFICATION": cv2.CAP_PROP_RECTIFICATION,
    "MONOCHROME": cv2.CAP_PROP_MONOCHROME,
    "SHARPNESS": cv2.CAP_PROP_SHARPNESS,
    "AUTO_WB": cv2.CAP_PROP_AUTO_WB,
    "BACKLIGHT": cv2.CAP_PROP_BACKLIGHT,
    "TEMPERATURE": cv2.CAP_PROP_TEMPERATURE,
    "TRIGGER": cv2.CAP_PROP_TRIGGER,
}

# 取得して出力
for name, prop_id in params.items():
    value = cap.get(prop_id)
    print(f"{name}: {value}")